baseURL = "https://course.sjmd.space"
languageCode = "en-US"
defaultContentLanguage = "en"
title = "Orientation"
theme = "hugo-theme-teach"
themesdir = "../themes/"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]


[params]
	editURL = "https://github.com/killermann/sjmd-course-orientation/content"
	helpURL = "https://sjmd.space/help"
	description = "Social Justice, Minus Dogma Course"
	author = "Sam Killermann"
	showVisitedLinks = true
	disableBreadcrumb = false
	disableNextPrev = false
	themeVariant = "green"

[outputs]
	home = [ "HTML", "RSS", "JSON"]
